name: CI

on:
  push:
  pull_request:

jobs:
  debug:
    permissions:
      actions: read
      id-token: write
      contents: read
    uses: bdehamer/workflows/.github/workflows/oidc-dump.yml@main
